### ISSUE TITLE
Update topic config options if a topic gets imported again with different topic config options

### ISSUE THREAD

**Issue by pkruesi** [pmw-rp/topic-cloner#1]
### Background

We use [topic-cloner](https://github.com/pmw-rp/topic-cloner) to create topics in a GitOps way.
If a developer needs a new topic the developer add's an additional entry to the `topics.json` (which stores all our topics including the topic config options). [Topic-cloner](https://github.com/pmw-rp/topic-cloner), running in k8s, sees that the `topics.json` got changed and imports the topics into [Redpanda](https://www.redpanda.com/).
With this approach our developers do not have to log into [Redpanda](https://www.redpanda.com/) to create new topics. We also benefit, that all topics and its configuration are stored and versioned in git.

### Problem

[Topic-cloner](https://github.com/pmw-rp/topic-cloner) does **only** deploy/create new topics. If an already existing topic gets **topic config options changes** those changes do not get applied as [topic-cloner](https://github.com/pmw-rp/topic-cloner) does not touch already existing topics and its options.

### Feature request / Requirement

The [topic-cloner](https://github.com/pmw-rp/topic-cloner) should apply topic config options changes to existing topics.
- Topic-cloner should check if
  - topic already exist on Redpanda/Kafka
    - if not - create new topic specified like given in the `topics.json`
    - if exists - check if there are topic configuration options which have changed (deployed vs `topics.json`)
      - if yes -  topic-cloner should **update/apply** the changes like give in the `topics.json`
    
#### Example `topics.json`

```
{
  "example-topic-1": {
    "Name": "example-topic-1",
    "Partitions": 1,
    "Replicas": 3,
    "Configs": {
      "cleanup.policy": "delete",
      "compression.type": "producer",
      "flush.bytes": "262144",
      "flush.ms": "100",
      "initial.retention.local.target.bytes": "-1",
      "initial.retention.local.target.ms": "3600000",
      "max.message.bytes": "1048576",
      "message.timestamp.type": "CreateTime",
      "redpanda.remote.delete": "true",
      "redpanda.remote.read": "true",
      "redpanda.remote.write": "true",
      "retention.bytes": "-1",
      "retention.local.target.bytes": "-1",
      "retention.local.target.ms": "21600000",
      "retention.ms": "604800000",
      "segment.bytes": "134217728",
      "segment.ms": "1209600000",
      "write.caching": "false"
    }
  },
  "example-topic-2": {
    "Name": "example-topic-2",
    "Partitions": 1,
    "Replicas": 3,
    "Configs": {
      "cleanup.policy": "delete",
      "compression.type": "producer",
      "flush.bytes": "262144",
      "flush.ms": "100",
      "initial.retention.local.target.bytes": "-1",
      "initial.retention.local.target.ms": "3600000",
      "max.message.bytes": "1048576",
      "message.timestamp.type": "CreateTime",
      "redpanda.remote.delete": "true",
      "redpanda.remote.read": "true",
      "redpanda.remote.write": "true",
      "retention.bytes": "-1",
      "retention.local.target.bytes": "-1",
      "retention.local.target.ms": "21600000",
      "retention.ms": "604800000",
      "segment.bytes": "134217728",
      "segment.ms": "1209600000",
      "write.caching": "false"
    }
  }
}
```

**Comment by pmw-rp** [comment]
Thanks for this report!

Initial version of code now in place that does this. See details in https://github.com/pmw-rp/topic-cloner/pull/2

**Comment by pkruesi** [comment]
Thanks :pray: a lot for the implementation of this feature-request.
